model_list:
  - model_name: gpt
    litellm_params:
      model: gpt-5-codex
      api_key: os.environ/OPENAI_API_KEY

  - model_name: sonnet
    litellm_params:
      model: claude-sonnet-4-5-20250929
      api_key: os.environ/ANTHROPIC_API_KEY
      thinking: {
        "type": "enabled",
        "budget_tokens": 1024
      }
      cache_control_injection_points:
        - location: message
          role: system

mcp_servers:
  jetbrains_mcp:
    transport: sse
    url: "http://localhost:64343/sse"
    auth_type: "none"

litellm_settings:
  # PostgreSQL Configuration
  database_type: "prisma"
  database_url: os.environ/DATABASE_URL
  store_model_in_db: true

  # CRITICAL: Enable callbacks for DB storage AND OTEL
  success_callback: ["postgres", "otel"]
  failure_callback: ["postgres", "otel"]

  # OTEL Configuration
  otel: true
  otel_exporter: "otlp_http"
  otel_endpoint: "http://localhost:4318/v1/traces"
  otel_service_name: "litellm-proxy"
  otel_headers: ""

  # Redis Cache Configuration
  cache: true
  cache_params:
    type: redis
    ttl: 3600
    host: localhost
    port: 6379
    password: sk-1234

  # MCP Configuration
  mcp_aliases:
    "jetbrains": "jetbrains_mcp"

  # Additional logging
  set_verbose: true
  drop_params: true

general_settings:
  master_key: sk-1234
  database_url: os.environ/DATABASE_URL
  database_connection_pool_limit: 100
  store_model_in_db: true
  store_prompts_in_spend_logs: true
